### ISSUE TITLE
text too long now i can't delete it

### ISSUE THREAD

**Issue by jad00gar** [kevinwucodes/gmail-quick-links#45]
I created a quick link with a lengthy name now. I can't edit or delete it.
can you please help

**Comment by kevinwucodes** [comment]
If you dont mind hacking around a bit and you do not have a crazy amount of links, you could reset the links.

Quick links are stored via `chrome.storage` apis.  You can take a look at what is stored in your console window.  You can do this by going to your Chrome DevTools -> Console.  Be sure you switch the console scope to Gmail Quick links

![image](https://user-images.githubusercontent.com/1930629/73801934-da252c80-4770-11ea-996a-7792adadd01e.png)

Take a look at your chrome.storage area by doing `chrome.storage.sync.get(null, dataset => console.log(dataset))`.  Depending on the type of links you can, they will be saved under `accountList` or `linkList`.  AccountList are quick links specific to your logged in gmail account whereas `linkList` are quick links applicable to all logged in gmail accounts.  This is done this way because there are some individuals with multiple gmail accounts and they want either separate quick links per account or common links across all accounts.

Save the links by copying the urlHashes to a text file for now.

Find the link that is too long and determine if it's coming from `accountList` or `linkList`.  If it's coming from `accountList', you can delete the entire list by invoking the commands in your console
`chrome.storage.sync.remove('accountList')`

If coming from `linkList`, run:

`chrome.storage.sync.remove('linkList')`

This is a bit drastic, but should get the job done.  Just be sure to save your urlHashes so that once you purge your lists, you can reapply them.
